<?xml version="1.0" encoding="UTF-8"?>

<!-- Generated by AutoCoder 
    Author: {{author}}
    Create: 2018-05-12
 -->
 
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
    <changeSet id="initial-01" author="{{author}}" runOnChange="true">
    {% for model in models %}
        <createTable tableName="{{model.name}}"{%+ if model.remark %} remarks="{{model.remark}}"{% endif %}>
        {% for col in model.columns %}
            <column name="{{col.name}}" type="{{col.type|lower}}"{%+ if col.remarks %} remarks="{{col.remarks}}"{% endif %}{%+ if col.default %}{%+ if col.type == "timestamp" %} defaultValueComputed="{{col.default}}"{% else %} defaultValue="{{col.default}}"{% endif %}{% endif %}{%+ if col.isAutoIncrease %} autoIncrement="true"{%endif%}>
                <constraints nullable="{{col.isNullable|lower}}"{%+ if col.isPrimary %} primaryKey="true"{% endif %}{%+ if col.isUnique %} unique="true"{% endif %}/>
            </column>
        {% endfor %}
            <column name="gmt_created" type="timestamp" defaultValueComputed="CURRENT_TIMESTAMP" remarks="创建时间（系统自动生成）">
                <constraints nullable="false"/>
            </column>
            <column name="gmt_modified" type="timestamp" remarks="最后修改时间（系统自动生成）">
                <constraints nullable="true"/>
            </column>
        </createTable>
        {% for ic in model.IndexConstraint %}
        <createIndex indexName="{{ic.name}}"
                     tableName="{{ic.baseTabelName}}"
                     unique="true">
            <column name="{{ic.baseColumn}}" type="{{ic.baseColumnType|lower}}"/>
        </createIndex>
        {% endfor %}
    {% endfor %}
        <rollback>
    {% for model in models %}
            <dropTable tableName="{{model.name}}"/>
    {% endfor %}
        </rollback>
    </changeSet>
</databaseChangeLog>

