<?xml version="1.0" encoding="UTF-8"?>

<!-- Generated by AutoCoder 
    Author: {{author}}
    Create: 2018-05-12
 -->

<databaseChangeLog
xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
    {% for file in changelogs %}
    <include file="{{file}}" relativeToChangelogFile="true"/>
    {% endfor %}
</databaseChangeLog>